# TCL File Generated by Component Editor 18.1
# Mon Nov 09 22:17:59 MSK 2020
# DO NOT MODIFY


# 
# multiplexer "multiplexer" v1.0
# Aulendil 2020.11.09.22:17:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module multiplexer
# 
set_module_property DESCRIPTION ""
set_module_property NAME user_multiplexer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Aulendil
set_module_property DISPLAY_NAME user_multiplexer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaboration

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL multiplexer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file multiplexer.sv SYSTEM_VERILOG PATH SIM/multiplexer.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter data_width INTEGER 32
set_parameter_property data_width DEFAULT_VALUE 32
set_parameter_property data_width DISPLAY_NAME "Width data"
set_parameter_property data_width TYPE INTEGER
set_parameter_property data_width ALLOWED_RANGES {8 16 32 64 128 256 512 1024 2048 4096}
set_parameter_property data_width UNITS None
set_parameter_property data_width HDL_PARAMETER true

add_parameter empty_width INTEGER 2
set_parameter_property empty_width DEFAULT_VALUE 2
set_parameter_property empty_width DISPLAY_NAME empty_width
set_parameter_property empty_width TYPE INTEGER
set_parameter_property empty_width UNITS None
set_parameter_property empty_width HDL_PARAMETER true
set_parameter_property empty_width VISIBLE false



add_parameter channel_width_gui INTEGER 1
set_parameter_property channel_width_gui DEFAULT_VALUE 1
set_parameter_property channel_width_gui DISPLAY_NAME "Width channel"
set_parameter_property channel_width_gui TYPE INTEGER
set_parameter_property channel_width_gui ALLOWED_RANGES {0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 25 26 27 28 29 30 31 32}
set_parameter_property channel_width_gui UNITS None
set_parameter_property channel_width_gui HDL_PARAMETER true



add_parameter channel_width INTEGER 1
set_parameter_property channel_width DEFAULT_VALUE 1
set_parameter_property channel_width DISPLAY_NAME "Width channel"
set_parameter_property channel_width TYPE INTEGER
set_parameter_property channel_width ALLOWED_RANGES {0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 25 26 27 28 29 30 31 32}
set_parameter_property channel_width UNITS None
set_parameter_property channel_width HDL_PARAMETER true
set_parameter_property channel_width VISIBLE FALSE
set_parameter_property channel_width DERIVED true
# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avsi_channel_0
# 
add_interface avsi_channel_0 avalon_streaming end
set_interface_property avsi_channel_0 associatedClock clock
set_interface_property avsi_channel_0 associatedReset reset
set_interface_property avsi_channel_0 dataBitsPerSymbol 8
set_interface_property avsi_channel_0 errorDescriptor ""
set_interface_property avsi_channel_0 firstSymbolInHighOrderBits true
set_interface_property avsi_channel_0 readyLatency 0
set_interface_property avsi_channel_0 ENABLED true
set_interface_property avsi_channel_0 EXPORT_OF ""
set_interface_property avsi_channel_0 PORT_NAME_MAP ""
set_interface_property avsi_channel_0 CMSIS_SVD_VARIABLES ""
set_interface_property avsi_channel_0 SVD_ADDRESS_GROUP ""


add_interface_port avsi_channel_0 avsi_one_data data Input data_width
add_interface_port avsi_channel_0 avsi_one_empty empty Input empty_width
add_interface_port avsi_channel_0 avsi_one_eop endofpacket Input 1
add_interface_port avsi_channel_0 avsi_one_ready ready Output 1
add_interface_port avsi_channel_0 avsi_one_sop startofpacket Input 1
add_interface_port avsi_channel_0 avsi_one_valid valid Input 1


# 
# connection point avsi_channel_1
# 
add_interface avsi_channel_1 avalon_streaming end
set_interface_property avsi_channel_1 associatedClock clock
set_interface_property avsi_channel_1 associatedReset reset
set_interface_property avsi_channel_1 dataBitsPerSymbol 8
set_interface_property avsi_channel_1 errorDescriptor ""
set_interface_property avsi_channel_1 firstSymbolInHighOrderBits true
set_interface_property avsi_channel_1 readyLatency 0
set_interface_property avsi_channel_1 ENABLED true
set_interface_property avsi_channel_1 EXPORT_OF ""
set_interface_property avsi_channel_1 PORT_NAME_MAP ""
set_interface_property avsi_channel_1 CMSIS_SVD_VARIABLES ""
set_interface_property avsi_channel_1 SVD_ADDRESS_GROUP ""


add_interface_port avsi_channel_1 avsi_two_data data Input data_width
add_interface_port avsi_channel_1 avsi_two_empty empty Input empty_width
add_interface_port avsi_channel_1 avsi_two_eop endofpacket Input 1
add_interface_port avsi_channel_1 avsi_two_ready ready Output 1
add_interface_port avsi_channel_1 avsi_two_sop startofpacket Input 1
add_interface_port avsi_channel_1 avsi_two_valid valid Input 1


# 
# connection point avso
# 
add_interface avso avalon_streaming start
set_interface_property avso associatedClock clock
set_interface_property avso associatedReset reset
set_interface_property avso dataBitsPerSymbol 8
set_interface_property avso errorDescriptor ""
set_interface_property avso firstSymbolInHighOrderBits true
set_interface_property avso readyLatency 0
set_interface_property avso ENABLED true
set_interface_property avso EXPORT_OF ""
set_interface_property avso PORT_NAME_MAP ""
set_interface_property avso CMSIS_SVD_VARIABLES ""
set_interface_property avso SVD_ADDRESS_GROUP ""


add_interface_port avso avso_data data Output data_width
add_interface_port avso avso_empty empty Output empty_width
add_interface_port avso avso_eop endofpacket Output 1
add_interface_port avso avso_ready ready Input 1
add_interface_port avso avso_sop startofpacket Output 1
add_interface_port avso avso_valid valid Output 1




proc elaboration {} {

	set current_channel_width [get_parameter_value channel_width_gui]
	set cnt_channel [expr pow(2,$current_channel_width) - 1]


	if {$current_channel_width>0} {
		add_interface_port avsi_channel_0 avsi_one_channel channel Input $current_channel_width
		add_interface_port avsi_channel_1 avsi_two_channel channel Input $current_channel_width
		add_interface_port avso avso_channel channel Output $current_channel_width
	}

	if {$current_channel_width>0} {
		set_parameter_value channel_width $current_channel_width
	} else {
		set_parameter_value channel_width 1
	}
	

	if {$current_channel_width>0} {
		set_interface_property avsi_channel_0 maxChannel $cnt_channel
		set_interface_property avsi_channel_1 maxChannel $cnt_channel
		set_interface_property avso maxChannel $cnt_channel
	} else {
		set_interface_property avsi_channel_0 maxChannel 0
		set_interface_property avsi_channel_1 maxChannel 0
		set_interface_property avso maxChannel 0
	}


}



